# config/default_params.yaml
#
# Example configuration file to configure a `kangaroo_x2_component`

/**:
  ros__parameters:
    general:
      control_freq: 20.0 # Control frequency -> frequency of the main thread
      debug_mode: false # true to activate debug messages

    comm:
      serial_port: "/dev/ttyUSB0" # serial port name
      baudrate: 115200 # serial baudrate
      timeout_msec: 1000 # data communication timeout in msec
      kx2_address: 128 # Kangaroo x2 address. Use the 'DEScribe' sw to configure
      kx2_drive_channel: 'D' # Kangaroo x2 name of the drive channel. Use the 'DEScribe' sw to configure
      kx2_turn_channel: 'T' # Kangaroo x2 name of the drive channel. Use the 'DEScribe' sw to configure

    diff_drive:
      wheel_radius_mm: 90.0 # Radius of the wheels [mm]
      track_width_mm: 320.0 # Distance between the middle of the wheels [mm]
      max_drive_accel: 1000 # Maximum drive acceleration [mm/s²]
      max_turn_accel: 360 # Maximum drive acceleration [°/s²]
      publish_tf: true # Set to false to disable TP broadcasting and fuse the `odom` messages with an external Kalman Filter
      odom_frame_id: 'base_link' # Frame id for odometry messages      

    encoder:
      lines: 100 # The counting feature of the encoder [Pulse per Round (PPR) or lines]. That is CPR/4 [Counts per Round]
      gear_ratio: 18.3 # Motor gear ration according to where the encoder is mounted on the motor -> gear_ratio:1
