# config/default_params.yaml
#
# Example configuration file to configure a `kangaroo_x2_component`

/**:
  ros__parameters:
    general:
      debug_mode: true # true to activate debug messages

    comm:
      serial_port: '/dev/tty0' # serial port name
      baudrate: 115200 # serial baudrate
      timeout_msec: 1000 # data communication timeout in msec

    diff_drive:
      wheel_radius_mm: 90 # Radius of the wheels [mm]
      track_width_mm: 320 # Distance between the middle of the wheels [mm]

    encoder:
      lines: 100 # The counting feature of the encoder [Pulse per Round (PPR) or lines]. That is CPR/4 [Counts per Round]
